import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# 1. Page Configuration
st.set_page_config(page_title="Climate Trend Analyzer", page_icon="🌍", layout="wide")

st.title("🌍 Climate Trend & Anomaly Dashboard")
st.markdown("""
This dashboard visualizes two decades of simulated climate data, highlighting long-term temperature trends, 
seasonal shifts, and extreme weather anomalies detected using Machine Learning (Isolation Forest).
""")

# 2. Load the Processed Data
@st.cache_data
def load_data():
    # Load the data generated by main.py
    df = pd.read_csv('data/processed/final_analyzed_data.csv')
    df['Date'] = pd.to_datetime(df['Date'])
    return df

try:
    df = load_data()
    
    # 3. Top-Level Metrics (KPIs)
    st.subheader("📊 High-Level Insights")
    col1, col2, col3, col4 = st.columns(4)
    
    total_days = len(df)
    anomalies_count = len(df[df['Anomaly'] == -1])
    avg_temp = df['Temperature_C'].mean()
    max_temp = df['Temperature_C'].max()
    
    col1.metric("Total Days Analyzed", f"{total_days:,}")
    col2.metric("Anomalies Detected", f"{anomalies_count}", delta="Extreme Events", delta_color="inverse")
    col3.metric("Average Temperature", f"{avg_temp:.2f} °C")
    col4.metric("Max Recorded Temp", f"{max_temp:.1f} °C")
    
    st.divider()

    # 4. Interactive Temperature Trend & Anomalies
    st.subheader("📈 Long-Term Temperature Trends & Extreme Anomalies")
    
    # Create an interactive Plotly chart
    fig_temp = go.Figure()
    
    # Add normal days
    normal_data = df[df['Anomaly'] == 1]
    fig_temp.add_trace(go.Scatter(
        x=normal_data['Date'], y=normal_data['Temperature_C'], 
        mode='markers', name='Normal Weather', marker=dict(color='lightblue', size=4, opacity=0.5)
    ))
    
    # Add anomaly days in Red
    anomaly_data = df[df['Anomaly'] == -1]
    fig_temp.add_trace(go.Scatter(
        x=anomaly_data['Date'], y=anomaly_data['Temperature_C'], 
        mode='markers', name='Anomaly (Extreme)', marker=dict(color='red', size=8, symbol='x')
    ))
    
    # Add 30-day moving average trend line
    fig_temp.add_trace(go.Scatter(
        x=df['Date'], y=df['Temp_30d_Avg'], 
        mode='lines', name='30-Day Trend', line=dict(color='orange', width=2)
    ))
    
    fig_temp.update_layout(xaxis_title="Year", yaxis_title="Temperature (°C)", hovermode="x unified")
    st.plotly_chart(fig_temp, use_container_width=True)

    st.divider()

    # 5. Seasonality & Rainfall
    col_left, col_right = st.columns(2)
    
    with col_left:
        st.subheader("🌦️ Monthly Temperature Distribution")
        # Boxplot using Plotly Express
        fig_box = px.box(df, x='Month', y='Temperature_C', color='Season', 
                         title="Seasonality (Boxplot)", 
                         labels={'Temperature_C': 'Temperature (°C)'})
        st.plotly_chart(fig_box, use_container_width=True)
        
    with col_right:
        st.subheader("🌧️ Rainfall vs Humidity")
        # Scatter plot for rainfall and humidity
        fig_scatter = px.scatter(df, x='Humidity_pct', y='Rainfall_mm', color='Season',
                                 title="Humidity vs. Rainfall Patterns",
                                 labels={'Humidity_pct': 'Humidity (%)', 'Rainfall_mm': 'Rainfall (mm)'})
        st.plotly_chart(fig_scatter, use_container_width=True)

    # 6. Raw Data Table (Optional View)
    with st.expander("View Raw Anomaly Data"):
        st.dataframe(anomaly_data[['Date', 'Temperature_C', 'Humidity_pct', 'Rainfall_mm', 'Season']].sort_values('Date', ascending=False))

except FileNotFoundError:
    st.error("🚨 Processed data not found! Please run `python main.py` first to generate the dataset.")